import axios from 'axios';
import { isArray } from 'util';

async function getPriceByRegion(region: number) {
  try {
    const { data } = await axios.get('/_spa_scipts/stocks.json');

    return region in data ? data[region] : data[0];
  } catch (error) {
    window.console.error(error);
  }
}

function getPrice(tariffId: number, data: any) {
  const price = data[tariffId];

  if (isArray(price)) {
    return price;
  }
  return [price, price, 0];
}

const TariffList = async (codeRigion: number) => {
  try {
    const price = await getPriceByRegion(codeRigion);

    return [
      {
        name: 'Удобный',
        sale: getPrice(0, price)[2],
        basePrice: getPrice(0, price)[0],
        price: getPrice(0, price)[1],
        paymentPeriod: 'год',
        paymentLabel: 'Минимальный старт',
        url: 'https://taxcom.ru/upload/tariff/region_77/2019/18042019_77_TP%20Udobnyy.pdf',
        priceTitle: 'Онлайн-Спринтер',
        isRecommended: false,
        isSpecialMode: false,
        necessaryServices: [
          'Электронная подпись',
          'Проверка на ошибки',
          'Умный календарь бухгалтера',
          'Обучение и семинары',
          'Такском-Информер',
          'Электронный больничный',
          'Сверка по НДС',
          'Формы отчетов',
          'Вероятность проверки ФНС',
          'Техподдержка 24/7',
        ],
        exchangeDirections: [
          {
            name: 'EDOFNS',
            displayName: 'ФНС',
            atExtraCost: false,
            sortOrder: 1,
            min: 1,
            max: 9999999,
          },
          {
            name: 'EDOPFR',
            displayName: 'ПФР',
            atExtraCost: false,
            sortOrder: 2,
            min: 1,
            max: 9999999,
          },
          {
            name: 'EDOFSS',
            displayName: 'ФСС',
            atExtraCost: true,
            sortOrder: 3,
            price: 3200,
            min: 0,
            max: 9999999,
          },
          {
            name: 'EDORS',
            displayName: 'Росстат',
            atExtraCost: true,
            sortOrder: 4,
            price: 3200,
            min: 0,
            max: 9999999,
          },
          {
            name: 'EDORP',
            displayName: 'РПН',
            atExtraCost: true,
            sortOrder: 5,
            price: 3200,
            min: 0,
            max: 9999999,
          },
          {
            name: 'EDOBR',
            displayName: 'ЦБ',
            atExtraCost: true,
            sortOrder: 6,
            price: 3200,
            min: 0,
            max: 9999999,
          },
        ],
        settings: [
          {
            settingName: 'SMS',
            settingDisplayName: 'СМС-уведомления',
            description: '',
            atExtraCost: true,
            sortOrder: 9,
            min: 0,
            max: 9999999,
          },
          {
            settingName: 'Learn',
            settingDisplayName: 'Выезд, настройка и обучение',
            description: 'Выезд, настройка и обучение',
            atExtraCost: true,
            sortOrder: 13,
            min: 0,
            max: 3,
          },
        ],
        gko: {
          min: 0,
          max: 3,
        },
        shortDescription: 'Отчеты в ФНС, ПФР, сервисы «Досье», «Сверься!», ЭДО с контрагентами',
        isPromo: false,
      },
      {
        name: 'Комфортный',
        sale: getPrice(1, price)[2],
        basePrice: getPrice(1, price)[0],
        price: getPrice(1, price)[1],
        paymentPeriod: 'год',
        paymentLabel: 'Стандартное решение',
        url: 'https://taxcom.ru/upload/tariff/region_77/2019/18042019_77_TP%20Udobnyy.pdf',
        priceTitle: 'Онлайн-Спринтер',
        isRecommended: false,
        isSpecialMode: false,
        necessaryServices: [
          'Электронная подпись',
          'Проверка на ошибки',
          'Умный календарь бухгалтера',
          'Обучение и семинары',
          'Такском-Информер',
          'Электронный больничный',
          'Сверка по НДС',
          'Формы отчетов',
          'Вероятность проверки ФНС',
          'Техподдержка 24/7',
        ],
        exchangeDirections: [
          {
            name: 'EDOFNS',
            displayName: 'ФНС',
            atExtraCost: false,
            sortOrder: 1,
            min: 1,
            max: 9999999,
          },
          {
            name: 'EDOPFR',
            displayName: 'ПФР',
            atExtraCost: false,
            sortOrder: 2,
            min: 1,
            max: 9999999,
          },
          {
            name: 'EDOFSS',
            displayName: 'ФСС',
            atExtraCost: false,
            sortOrder: 3,
            min: 0,
            max: 9999999,
          },
          {
            name: 'EDORS',
            displayName: 'Росстат',
            atExtraCost: true,
            sortOrder: 4,
            price: 3500,
            min: 0,
            max: 9999999,
          },
          {
            name: 'EDORP',
            displayName: 'РПН',
            atExtraCost: true,
            sortOrder: 5,
            price: 3500,
            min: 0,
            max: 9999999,
          },

          {
            name: 'EDOBR',
            displayName: 'ЦБ',
            atExtraCost: true,
            sortOrder: 6,
            price: 3500,
            min: 0,
            max: 9999999,
          },
        ],
        settings: [
          {
            settingName: 'ES_CD',
            settingDisplayName: 'Электронный документооборот с партнерами',
            description: '5 000 исходящих документов',
            atExtraCost: false,
            sortOrder: 10,
            min: 0,
            max: 3,
          },
          {
            settingName: 'ES_CD2',
            settingDisplayName: 'Проверка контрагентов',
            description: '1 лицензия на Такском-Досье',
            tooltip: 'Контактные, финансовые и судебные данные обо всех компаниях и предпринимателях России',
            atExtraCost: false,
            sortOrder: 10,
            min: 0,
            max: 3,
          },
          {
            settingName: 'SMS',
            settingDisplayName: 'СМС-уведомления',
            description: 'Рассылка SMS',
            atExtraCost: true,
            sortOrder: 9,
            min: 0,
            max: 9999999,
          },
          {
            settingName: 'AdditionalLogins',
            settingDisplayName: 'Дополнительные рабочие места',
            description: 'Дополнительные рабочие места',
            atExtraCost: true,
            sortOrder: 12,
            min: 1,
            max: 1,
          },
          {
            settingName: 'Learn',
            settingDisplayName: 'Выезд, настройка и обучение',
            description: 'Выезд, настройка и обучение',
            atExtraCost: true,
            sortOrder: 13,
            min: 0,
            max: 3,
          },
        ],
        gko: {
          min: 0,
          max: 3,
        },
        shortDescription: 'Отчеты в ФНС, ПФР, сервисы «Досье», «Сверься!», ЭДО с контрагентами',
        isPromo: false,
      },
      {
        name: 'Удобный',
        sale: getPrice(2, price)[2],
        basePrice: getPrice(2, price)[0],
        price: getPrice(2, price)[1],
        paymentPeriod: 'год',
        paymentLabel: 'Минимальный старт',
        url: 'https://taxcom.ru/upload/tariff/region_77/2019/18042019_77_TP%20Komfortnyy.pdf',
        priceTitle: 'Онлайн-Спринтер',
        isRecommended: false,
        isSpecialMode: true,
        necessaryServices: [
          'Электронная подпись',
          'Проверка на ошибки',
          'Умный календарь бухгалтера',
          'Обучение и семинары',
          'Такском-Информер',
          'Электронный больничный',
          'Сверка по НДС',
          'Формы отчетов',
          'Вероятность проверки ФНС',
          'Техподдержка 24/7',
        ],
        exchangeDirections: [
          {
            name: 'EDOBR',
            displayName: 'ЦБ',
            atExtraCost: true,
            sortOrder: 6,
            price: 3200,
            min: 0,
            max: 9999999,
          },
          {
            name: 'EDOFNS',
            displayName: 'ФНС',
            atExtraCost: false,
            sortOrder: 1,
            min: 1,
            max: 9999999,
          },
          {
            name: 'EDOFSS',
            displayName: 'ФСС',
            atExtraCost: true,
            sortOrder: 3,
            price: 3200,
            min: 1,
            max: 9999999,
          },
          {
            name: 'EDOPFR',
            displayName: 'ПФР',
            atExtraCost: false,
            sortOrder: 2,
            price: 3200,
            min: 1,
            max: 9999999,
          },
          {
            name: 'EDORP',
            displayName: 'РПН',
            atExtraCost: true,
            sortOrder: 5,
            price: 3200,
            min: 0,
            max: 9999999,
          },
          {
            name: 'EDORS',
            displayName: 'Росстат',
            atExtraCost: true,
            sortOrder: 4,
            price: 3200,
            min: 0,
            max: 9999999,
          },
        ],
        settings: [
          {
            settingName: 'SMS',
            settingDisplayName: 'СМС-уведомления',
            description: '',
            atExtraCost: true,
            sortOrder: 9,
            min: 0,
            max: 9999999,
          },
          {
            settingName: 'Learn',
            settingDisplayName: 'Выезд, настройка и обучение',
            description: 'Выезд, настройка и обучение',
            atExtraCost: true,
            sortOrder: 13,
            min: 0,
            max: 3,
          },
        ],
        gko: {
          min: 0,
          max: 3,
        },
        shortDescription: 'Отчеты в ФНС, ПФР, ФСС, сервисы «Досье», «Сверься!», ЭДО с контрагентами',
        isPromo: false,
      },
      {
        name: 'Комфортный',
        sale: getPrice(3, price)[2],
        basePrice: getPrice(3, price)[0],
        price: getPrice(3, price)[1],
        paymentPeriod: 'год',
        paymentLabel: 'Стандартное решение',
        url: 'https://taxcom.ru/upload/tariff/region_77/2019/18042019_77_TP%20Komfortnyy%20Sp.pdf',
        priceTitle: 'Онлайн-Спринтер',
        isRecommended: false,
        isSpecialMode: true,
        necessaryServices: [
          'Электронная подпись',
          'Проверка на ошибки',
          'Умный календарь бухгалтера',
          'Обучение и семинары',
          'Такском-Информер',
          'Электронный больничный',
          'Сверка по НДС',
          'Формы отчетов',
          'Вероятность проверки ФНС',
          'Техподдержка 24/7',
        ],
        exchangeDirections: [
          {
            name: 'EDOBR',
            displayName: 'ЦБ',
            atExtraCost: true,
            sortOrder: 6,
            price: 3500,
            min: 0,
            max: 9999999,
          },
          {
            name: 'EDOFNS',
            displayName: 'ФНС',
            atExtraCost: false,
            sortOrder: 1,
            min: 1,
            max: 9999999,
          },
          {
            name: 'EDOFSS',
            displayName: 'ФСС',
            atExtraCost: false,
            sortOrder: 3,
            min: 1,
            max: 9999999,
          },
          {
            name: 'EDOPFR',
            displayName: 'ПФР',
            atExtraCost: false,
            sortOrder: 2,
            min: 1,
            max: 9999999,
          },
          {
            name: 'EDORP',
            displayName: 'РПН',
            atExtraCost: true,
            sortOrder: 5,
            price: 3500,
            min: 0,
            max: 9999999,
          },
          {
            name: 'EDORS',
            displayName: 'Росстат',
            atExtraCost: true,
            sortOrder: 4,
            price: 3500,
            min: 0,
            max: 9999999,
          },
        ],
        settings: [
          {
            settingName: 'ES_CD',
            settingDisplayName: 'Электронный документооборот с партнерами',
            description: '5 000 исходящих документов',
            atExtraCost: false,
            sortOrder: 10,
            min: 0,
            max: 3,
          },
          {
            settingName: 'ES_CD2',
            settingDisplayName: 'Проверка контрагентов',
            description: '1 лицензия на Такском-Досье',
            tooltip: 'Контактные, финансовые и судебные данные обо всех компаниях и предпринимателях России',
            atExtraCost: false,
            sortOrder: 10,
            min: 0,
            max: 3,
          },
          {
            settingName: 'SMS',
            settingDisplayName: 'СМС-уведомления',
            description: 'Рассылка SMS',
            atExtraCost: true,
            sortOrder: 9,
            min: 0,
            max: 9999999,
          },
          {
            settingName: 'AdditionalLogins',
            settingDisplayName: 'Дополнительные рабочие места',
            description: 'Дополнительные рабочие места',
            atExtraCost: true,
            sortOrder: 12,
            min: 1,
            max: 1,
          },
          {
            settingName: 'Learn',
            settingDisplayName: 'Выезд, настройка и обучение',
            description: 'Выезд, настройка и обучение',
            atExtraCost: true,
            sortOrder: 13,
            min: 0,
            max: 3,
          },
        ],
        gko: {
          min: 0,
          max: 3,
        },
        shortDescription: 'Отчеты в ФНС, ПФР, ФСС, сервисы «Досье», «Сверься!», ЭДО с контрагентами',
        isPromo: false,
      },
      {
        name: 'Солидный',
        sale: getPrice(4, price)[2],
        basePrice: getPrice(4, price)[0],
        price: getPrice(4, price)[1],
        paymentPeriod: 'год',
        paymentLabel: 'Полноценная работа для всех',
        url: 'https://taxcom.ru/upload/tariff/region_77/2019/18042019_77_TP%20Solidnyy.pdf',
        priceTitle: 'Онлайн-Спринтер',
        isRecommended: true,
        isSpecialMode: false,
        necessaryServices: [
          'Электронная подпись',
          'Проверка на ошибки',
          'Умный календарь бухгалтера',
          'Обучение и семинары',
          'Такском-Информер',
          'Электронный больничный',
          'Сверка по НДС',
          'Формы отчетов',
          'Вероятность проверки ФНС',
          'Техподдержка 24/7',
        ],
        exchangeDirections: [
          {
            name: 'EDOBR',
            displayName: 'ЦБ РФ',
            atExtraCost: false,
            sortOrder: 6,
            min: 1,
            max: 9999999,
          },
          {
            name: 'EDOFNS',
            displayName: 'ФНС',
            atExtraCost: false,
            sortOrder: 1,
            min: 1,
            max: 9999999,
          },
          {
            name: 'EDOFSS',
            displayName: 'ФСС',
            atExtraCost: false,
            sortOrder: 3,
            min: 1,
            max: 9999999,
          },
          {
            name: 'EDOPFR',
            displayName: 'ПФР',
            atExtraCost: false,
            sortOrder: 2,
            min: 1,
            max: 9999999,
          },
          {
            name: 'EDORP',
            displayName: 'РПН',
            atExtraCost: false,
            sortOrder: 5,
            min: 1,
            max: 9999999,
          },
          {
            name: 'EDORS',
            displayName: 'Росстат',
            atExtraCost: false,
            sortOrder: 4,
            min: 1,
            max: 9999999,
          },
        ],
        settings: [
          {
            settingName: 'ES_CD',
            settingDisplayName: 'Электронный документооборот с партнерами',
            description: '100 000 исходящих документов',
            atExtraCost: false,
            sortOrder: 10,
            min: 0,
            max: 3,
          },
          {
            settingName: 'ES_CD',
            settingDisplayName: 'Проверка контрагентов',
            description: '5 лицензий на Такском-Досье',
            tooltip: 'Контактные, финансовые и судебные данные обо всех компаниях и предпринимателях России',
            atExtraCost: false,
            sortOrder: 10,
            min: 0,
            max: 3,
          },
          {
            settingName: 'SMS',
            settingDisplayName: 'СМС-уведомления',
            description: 'Рассылка SMS',
            atExtraCost: true,
            sortOrder: 9,
            min: 0,
            max: 9999999,
          },
          {
            settingName: 'FailerDocs',
            settingDisplayName: 'Дополнительные рабочие места',
            description: 'Дополнительные рабочие места',
            atExtraCost: true,
            sortOrder: 11,
            min: 1,
            max: 1,
          },
          {
            settingName: 'Learn',
            settingDisplayName: 'Выезд, настройка и обучение',
            description: 'Выезд, настройка и обучение',
            atExtraCost: true,
            sortOrder: 13,
            min: 0,
            max: 3,
          },
        ],
        gko: {
          min: 0,
          max: 3,
        },
        shortDescription:
          'Сдача отчетности в ФНС, ПФР, Росстат, ФСС, Росприроднадзор, ЦБ и множество дополнительных возможностей.',
        isPromo: false,
      },
      {
        name: 'Солидный',
        sale: getPrice(5, price)[2],
        basePrice: getPrice(5, price)[0],
        price: getPrice(5, price)[1],
        paymentPeriod: 'год',
        paymentLabel: 'Полноценная работа для всех',
        url: 'https://taxcom.ru/upload/tariff/region_77/2019/18042019_77_TP%20Solidnyy%20Sp.pdf',
        priceTitle: 'Онлайн-Спринтер',
        isRecommended: true,
        isSpecialMode: true,
        necessaryServices: [
          'Электронная подпись',
          'Проверка на ошибки',
          'Умный календарь бухгалтера',
          'Обучение и семинары',
          'Такском-Информер',
          'Электронный больничный',
          'Сверка по НДС',
          'Формы отчетов',
          'Вероятность проверки ФНС',
          'Техподдержка 24/7',
        ],
        exchangeDirections: [
          {
            name: 'EDOBR',
            displayName: 'ЦБ РФ',
            atExtraCost: false,
            sortOrder: 6,
            min: 1,
            max: 9999999,
          },
          {
            name: 'EDOFNS',
            displayName: 'ФНС',
            atExtraCost: false,
            sortOrder: 1,
            min: 1,
            max: 9999999,
          },
          {
            name: 'EDOFSS',
            displayName: 'ФСС',
            atExtraCost: false,
            sortOrder: 3,
            min: 1,
            max: 9999999,
          },
          {
            name: 'EDOPFR',
            displayName: 'ПФР',
            atExtraCost: false,
            sortOrder: 2,
            min: 1,
            max: 9999999,
          },
          {
            name: 'EDORP',
            displayName: 'РПН',
            atExtraCost: false,
            sortOrder: 5,
            min: 1,
            max: 9999999,
          },
          {
            name: 'EDORS',
            displayName: 'Росстат',
            atExtraCost: false,
            sortOrder: 4,
            min: 1,
            max: 9999999,
          },
        ],
        settings: [
          {
            settingName: 'ES_CD',
            settingDisplayName: 'Электронный документооборот с партнерами',
            description: '100 000 исходящих документов',
            atExtraCost: false,
            sortOrder: 10,
            min: 0,
            max: 3,
          },
          {
            settingName: 'ES_CD',
            settingDisplayName: 'Проверка контрагентов',
            description: '5 лицензий на Такском-Досье',
            tooltip: 'Контактные, финансовые и судебные данные обо всех компаниях и предпринимателях России',
            atExtraCost: false,
            sortOrder: 10,
            min: 0,
            max: 3,
          },
          {
            settingName: 'SMS',
            settingDisplayName: 'СМС-уведомления',
            description: 'Рассылка SMS',
            atExtraCost: true,
            sortOrder: 9,
            min: 0,
            max: 9999999,
          },
          {
            settingName: 'AdditionalLogins',
            settingDisplayName: 'Дополнительные рабочие места',
            description: 'Дополнительные рабочие места',
            atExtraCost: true,
            sortOrder: 11,
            min: 1,
            max: 1,
          },
          {
            settingName: 'Learn',
            settingDisplayName: 'Выезд, настройка и обучение',
            description: 'Выезд, настройка и обучение',
            atExtraCost: true,
            sortOrder: 13,
            min: 0,
            max: 3,
          },
        ],
        gko: {
          min: 0,
          max: 3,
        },
        shortDescription:
          'Сдача отчетности в ФНС, ПФР, Росстат, ФСС, Росприроднадзор, ЦБ и множество дополнительных возможностей.',
        isPromo: false,
      },
      {
        name: 'Ваш интерес',
        sale: getPrice(6, price)[2],
        basePrice: getPrice(6, price)[0],
        price: getPrice(6, price)[1],
        paymentPeriod: 'год',
        paymentLabel: 'Для группы компаний',
        url: 'https://taxcom.ru/upload/tariff/region_77/2019/01012019_77_TP_Vinteres.pdf',
        priceTitle: 'Доклайнер',
        isRecommended: false,
        isSpecialMode: false,
        necessaryServices: [
          'Электронная подпись',
          'Проверка на ошибки',
          'Умный календарь бухгалтера',
          'Обучение и семинары',
          'Такском-Информер',
          'Электронный больничный',
          'Сверка по НДС',
          'Формы отчетов',
          'Вероятность проверки ФНС',
          'Техподдержка 24/7',
          'Сводная таблица для контроля организаций на обслуживании',
          'Массовая отправка отчетов',
        ],
        exchangeDirections: [
          {
            name: 'EDOBR',
            displayName: 'ЦБ РФ',
            atExtraCost: false,
            sortOrder: 6,
            min: 0,
            max: 3,
          },
          {
            name: 'EDOFNS',
            displayName: 'ФНС',
            atExtraCost: false,
            sortOrder: 1,
            min: 0,
            max: 3,
          },
          {
            name: 'EDOFSS',
            displayName: 'ФСС',
            atExtraCost: false,
            sortOrder: 3,
            min: 0,
            max: 3,
          },
          {
            name: 'EDOPFR',
            displayName: 'ПФР',
            atExtraCost: false,
            sortOrder: 2,
            min: 0,
            max: 3,
          },
          {
            name: 'EDORP',
            displayName: 'РПН',
            atExtraCost: false,
            sortOrder: 5,
            min: 0,
            max: 3,
          },
          {
            name: 'EDORS',
            displayName: 'Росстат',
            atExtraCost: false,
            sortOrder: 4,
            min: 0,
            max: 3,
          },
        ],
        settings: [
          {
            settingName: 'ES_CD',
            settingDisplayName: 'Проверка контрагентов',
            description: '1 лицензия на Такском-Досье',
            tooltip: 'Контактные, финансовые и судебные данные обо всех компаниях и предпринимателях России',
            atExtraCost: false,
            sortOrder: 10,
            min: 0,
            max: 2,
          },
          {
            settingName: 'SMS',
            settingDisplayName: 'Одновременнная работа нескольких пользователей с разграничением прав',
            description: '',
            atExtraCost: false,
            sortOrder: 9,
            min: 0,
            max: 1,
          },
          {
            settingName: 'SMS',
            settingDisplayName: 'СМС-уведомления',
            description: '',
            atExtraCost: false,
            sortOrder: 9,
            min: 0,
            max: 1,
          },
          {
            settingName: 'FailerDocs',
            settingDisplayName: 'Электронный документооборот с партнерами',
            description: 'Электронный документооборот с партнерами',
            atExtraCost: true,
            sortOrder: 11,
            min: 1,
            max: 1,
          },
          {
            settingName: 'AdditionalLogins',
            settingDisplayName: 'Дополнительные рабочие места',
            description: 'Дополнительные рабочие места',
            atExtraCost: true,
            sortOrder: 12,
            min: 1,
            max: 1,
          },
          {
            settingName: 'Learn',
            settingDisplayName: 'Выезд, настройка и обучение',
            description: 'Выезд, настройка и обучение',
            atExtraCost: true,
            sortOrder: 13,
            min: 0,
            max: 3,
          },
          {
            settingName: 'ES_CD',
            settingDisplayName: 'Личный менеджер и курьерская доставка документов',
            description: 'Личный менеджер и курьерская доставка документов',
            atExtraCost: true,
            sortOrder: 13,
            min: 0,
            max: 3,
          },
        ],
        gko: {
          min: 0,
          max: 999999,
        },
        shortDescription:
          'Сдача отчетности в ФНС, ПФР, Росстат, ФСС, Росприроднадзор, ЦБ и множество дополнительных возможностей.',
        isPromo: false,
      },
      {
        name: 'Ваш интерес',
        sale: getPrice(7, price)[2],
        basePrice: getPrice(7, price)[0],
        price: getPrice(7, price)[1],
        paymentPeriod: 'год',
        paymentLabel: 'Для группы компаний',
        url: 'https://taxcom.ru/upload/tariff/region_77/2019/01012019_77_TP_Vinteres.pdf',
        priceTitle: 'Доклайнер',
        isRecommended: false,
        isSpecialMode: true,
        necessaryServices: [
          'Электронная подпись',
          'Проверка на ошибки',
          'Умный календарь бухгалтера',
          'Обучение и семинары',
          'Такском-Информер',
          'Электронный больничный',
          'Сверка по НДС',
          'Формы отчетов',
          'Вероятность проверки ФНС',
          'Техподдержка 24/7',
          'Сводная таблица для контроля организаций на обслуживании',
          'Массовая отправка отчетов',
        ],
        exchangeDirections: [
          {
            name: 'EDOBR',
            displayName: 'ЦБ РФ',
            atExtraCost: false,
            sortOrder: 6,
            min: 0,
            max: 3,
          },
          {
            name: 'EDOFNS',
            displayName: 'ФНС',
            atExtraCost: false,
            sortOrder: 1,
            min: 0,
            max: 3,
          },
          {
            name: 'EDOFSS',
            displayName: 'ФСС',
            atExtraCost: false,
            sortOrder: 3,
            min: 0,
            max: 3,
          },
          {
            name: 'EDOPFR',
            displayName: 'ПФР',
            atExtraCost: false,
            sortOrder: 2,
            min: 0,
            max: 3,
          },
          {
            name: 'EDORP',
            displayName: 'РПН',
            atExtraCost: false,
            sortOrder: 5,
            min: 0,
            max: 3,
          },
          {
            name: 'EDORS',
            displayName: 'Росстат',
            atExtraCost: false,
            sortOrder: 4,
            min: 0,
            max: 3,
          },
        ],
        settings: [
          {
            settingName: 'ES_CD',
            settingDisplayName: 'Проверка контрагентов',
            description: '1 лицензия на Такском-Досье',
            tooltip: 'Контактные, финансовые и судебные данные обо всех компаниях и предпринимателях России',
            atExtraCost: false,
            sortOrder: 10,
            min: 0,
            max: 2,
          },
          {
            settingName: 'SMS',
            settingDisplayName: 'Одновременнная работа нескольких пользователей с разграничением прав',
            description: '',
            atExtraCost: false,
            sortOrder: 9,
            min: 0,
            max: 1,
          },
          {
            settingName: 'SMS',
            settingDisplayName: 'СМС-уведомления',
            description: '',
            atExtraCost: false,
            sortOrder: 9,
            min: 0,
            max: 1,
          },
          {
            settingName: 'FailerDocs',
            settingDisplayName: 'Электронный документооборот с партнерами',
            description: 'Электронный документооборот с партнерами',
            atExtraCost: true,
            sortOrder: 11,
            min: 1,
            max: 1,
          },
          {
            settingName: 'AdditionalLogins',
            settingDisplayName: 'Дополнительные рабочие места',
            description: 'Дополнительные рабочие места',
            atExtraCost: true,
            sortOrder: 12,
            min: 1,
            max: 1,
          },
          {
            settingName: 'Learn',
            settingDisplayName: 'Выезд, настройка и обучение',
            description: 'Выезд, настройка и обучение',
            atExtraCost: true,
            sortOrder: 13,
            min: 0,
            max: 3,
          },
          {
            settingName: 'ES_CD',
            settingDisplayName: 'Личный менеджер и курьерская доставка документов',
            description: 'Личный менеджер и курьерская доставка документов',
            atExtraCost: true,
            sortOrder: 13,
            min: 0,
            max: 3,
          },
        ],
        gko: {
          min: 0,
          max: 999999,
        },
        shortDescription:
          'Сдача отчетности в ФНС, ПФР, Росстат, ФСС, Росприроднадзор, ЦБ и множество дополнительных возможностей.',
        isPromo: false,
      },
    ];
  } catch (error) {
    window.console.error(error);
  }
};

export default TariffList;
